services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    container_name: kafka
    hostname: kafka
    environment:
      - KAFKA_HEAP_OPTS=-Xmx256M -Xms128M
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://${INTERNAL_IP}:9092,EXTERNAL:${EXTERNAL_IP}//:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    ports:
      - 9093:9093
    depends_on:
      - zookeeper
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - /data/db:/data/db:rw
