services:
  zookeeper:
    image: aawaali/alpine-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: aawaali/alpine-kafka
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - /data/db:/data/db:rw
