services:
  zookeeper:
    image: aawaali/alpine-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: aawaali/alpine-kafka
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://${INTERNAL_IP}:9092,EXTERNAL://${EXTERNAL_IP}:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    ports:
      - 9092:9092
      - 19092:19092
    depends_on:
      - zookeeper
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - /data/db:/data/db:rw
